#!/usr/bin/env groovy

node {

    try{
        stage('checkout') {
        checkout scm
        }

        stage('check java') {
            sh "java -version"
            echo {env.BRANCH_NAME}
        }

    } catch (final e){
        currentBuild.result = 'FAILURE'
        throw e
    } finally {

    }

}

